### ISSUE TITLE
clarify license

### ISSUE THREAD

**Issue by mahf708** [ESMCI/mpi-serial#19]
@rljacob we would like to add this to conda-forge to solve an issue surrounding nco (and esmf) being broken without an explicit MPI. A challenge right now is the licensing. If no objections, could we formalize this license to follow one of these listed here https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions? If so, I could open a PR with the necessary edits. 

xref: https://github.com/conda-forge/staged-recipes/pull/22793

**Comment by rljacob** [comment]
BSD 3-clause is fine.
