### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by gold2718** [ESMCI/mpi-serial#3]
There is a general issue of documentation being out of date (e.g., README has not been updated in nearly 30 months). Some is easy -- add missing items to README. One question I have is about generation of files. The top of mpif.h says:
```
!!!
!!!   NOTE: The files mpif.realXdoubleY.h are generated from
!!!   mpif.master.h using make-mpif and later copied to mpif.h
!!!   during the library make.  All modifications should be
!!!   made to mpif.master.h
!!!
```
I cannot find any sign of this infrastructure. Is there any sort of code generation going on in mpi-serial? Any objections to getting rid of the comment?

Any objections to getting rid of NOTES? It seems ignored and out of date.

**Comment by rljacob** [comment]
Yes you can remove NOTES.   Yes you can get rid of that comment.  The code generation went away with the conversion to autotools.
